services:
  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_DATABASE=aimusing_development

  aimusing-service:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3033:3033"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/aimusing_development
      - PORT=3033
      - ENV=development
      - PREFIX=aimusing
      - PLATFORM_URL=http://localhost:3033
    depends_on:
      - mongodb
